Issue 001/subtask/issue 003/home page desktop implementation
IIWPEOJ-Inc/FlowersStore pull request #21
Opened 2023-08-24 21:36 UTC by Dustikdev

done header, homepage

2023-08-26 05:10 UTC, SimonShvets commented
@Dustikdev предлагаю перенести папку components из src в shared. Тк это по сути и есть shared components - компоненты используемые в рамках других страниц/компонентов

2023-08-27 10:25 UTC, SimonShvets commented on src/_functions.scss
> +﻿@function calculate-vw($value) {
вынести файл в shared/functions/_functions.scss

2023-08-27 10:25 UTC, SimonShvets commented on src/components/Header/Header.scss
> +  .mobile-only {
пока пусть будет так, но надо будет поправить, я в пул реквесте на футер приготовил компонент для использования в других классах для обработки responsive

2023-08-27 10:25 UTC, SimonShvets commented on src/components/Header/Header.tsx
> +import { useState } from 'react';
где здесь используешь useState?

2023-08-27 10:25 UTC, SimonShvets commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +          <SecondaryButton text={'LERN MORE'} status={''} />
Learn

2023-08-27 10:25 UTC, SimonShvets commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +          <h3>Kyiv LuxeBouquets</h3>
давай Kyiv на Montreal поправим

2023-08-27 10:25 UTC, SimonShvets commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +export const AboutUsSection = () => {
использование секции в нейминге это бедпрактис, так же как и в названии файлов у тебя и так внутри компонентов присутствует тег section так что любому программисту будет понятно что речь идет о секции

2023-08-27 10:25 UTC, SimonShvets commented on src/pages/Home/HeroSection/HeroSection.tsx
> +              Kyiv
Montreal

2023-08-27 10:25 UTC, SimonShvets commented on src/pages/Home/HeroSection/HeroSection.tsx
> +import { FlowerBlock } from './components/FlowerBlock/FlowerBlock';
если планируешь импортировать только один компонент, почему бы не сделать export default?

2023-08-27 10:25 UTC, SimonShvets commented on src/pages/Home/HeroSection/HeroSection.scss
> +    .r-item {
по названию хотелось бы понимать что из себя представляет стиль, не могу из названия определить что из себя представляет r-item

2023-08-27 10:25 UTC, SimonShvets commented on src/components/Header/Header.scss
> +      width: calculate-vw-mobile(24);
font-size так же является динамической величиной

2023-08-27 10:56 UTC, SimonShvets commented on src/pages/Home/HeroSection/components/DescriptionBlock/DescriptionBlock.tsx
> +  if (props.direction === Direction.Left) {
тернарный оператор здесь как будто лучше смотрится, плюс ты можешь использовать разметку img а не bottomLable тогда уйдет повторение строк разметки bottomLable

2023-08-27 10:56 UTC, SimonShvets commented on src/pages/Home/Home.tsx
> +      <div className="our-service">
с одной стороны не хочется делать отдельный компонент для подобной секции, но с другой стороны есть пара причин которые я вижу для сделать это:
1) расширяемость - мы не знаем что еще может заказчик в дальнейшем положить в эту секцию.
2) общий подход - мы описываем отдельные куски UI как компоненты, то есть придерживаемся компонентного подхода - подобные div внутри Home page для меня смотрятся странно, идет список компонентов и потом в середине вкоряченный див, хоть и небольшой, тогда вопрос сразу а почему он вообще не в отдельном компоненте или не относится к другому компоненту.

2023-08-27 10:56 UTC, SimonShvets commented on src/pages/Home/ReviewSection/ReviewSection.tsx
> +          <SwiperSlide>
выглядит так что ты можешь сделать общий компонент - обертку для Swiper, это нужно т к в Product странице присутствует функционал свайпера, например на вход можно было бы отдавать массив SwiperSlide для дальнейшего отображение, таким образом отделить контент наполнения свайпера от его стилизации и формы

2023-08-27 10:56 UTC, SimonShvets commented on src/pages/Home/WhyChooseUsSection/components/RightSideComponent/RightSideComponent.tsx
> +export const RightSideComponent = (props: RightSideComponentProps) => {
тоже самое - мы находимся в папке компонентов, зачем называть то что уже находится в директории компонентов - компонентом?

2023-08-27 10:56 UTC, SimonShvets commented on src/pages/Home/WhyChooseUsSection/components/RightSideComponent/RightSideComponent.tsx
> +export const RightSideComponent = (props: RightSideComponentProps) => {
обращение к Props можно деструктурировать если писать в при инициализации  сразу нужны свойства: 
export const RightSideComponent = ({ header, description}: RightSideComponentProps) =>

2023-08-27 10:58 UTC, SimonShvets commented on src/pages/Home/WhyChooseUsSection/components/RightSideComponent/RightSideComponent.tsx
> +export const RightSideComponent = (props: RightSideComponentProps) => {
это касается всех компонентов, естественно

2023-08-27 11:40 UTC, SimonShvets commented on package.json
>    },
добавь сюда секцию   
"overrides": {
    "react-scripts": {
      "typescript": "^5"
    }
  },
  для успешной сборки

2023-08-27 11:41 UTC, SimonShvets commented
макет едет:
<img width="1197" alt="image" src="https://github.com/IIWPEOJ-Inc/FlowersStore/assets/74120573/fdfec225-d81f-4e9c-ab8f-40e703a51a85">

2023-08-27 11:42 UTC, SimonShvets commented
разная жирность границ: 
<img width="735" alt="image" src="https://github.com/IIWPEOJ-Inc/FlowersStore/assets/74120573/e57f54bb-c548-4b73-86ba-74b078bf356c">

2023-08-27 11:42 UTC, SimonShvets commented on package.json
>    },
после секции dependencies

2023-08-27 12:26 UTC, Negodyaj commented on src/_functions.scss
> +﻿@function calculate-vw($value) {
только тогда уж в shared/mixins

2023-08-27 12:27 UTC, Negodyaj commented on src/components/Header/Header.scss
> +}
вот это надо в index.scss перенести, потому как это максимально глобальный стиль

2023-08-27 12:27 UTC, Negodyaj commented on src/components/Header/Header.scss
> +  }
и это тоже

2023-08-27 12:30 UTC, Negodyaj commented on src/components/TertiaryButton/TertiaryButton.scss
> +  }
теоретически, ты мог бы сделать класс common-button и вынести туда весь css, что у тебя в трёх компонентах дублируется

2023-08-27 12:32 UTC, Negodyaj commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +export const AboutUsSection = () => {
я бы не был столь категоричен, потому как со стороны компонента Home эти теги section не видны)

2023-08-27 12:33 UTC, Negodyaj commented on src/pages/Home/HeroSection/HeroSection.scss
> +          }
как будто класс italic можно вынести в общие

2023-08-27 12:34 UTC, Negodyaj commented on src/pages/Home/HeroSection/HeroSection.tsx
> +import { FlowerBlock } from './components/FlowerBlock/FlowerBlock';
вкусовщина)
мне тоже не нравится доп. строка с экспортом дефолта

2023-08-27 12:36 UTC, Negodyaj commented on src/pages/Home/Home.tsx
> +      <div className="our-service">
это я предложил не делать компонент)
мысли здравые
но это же, блин, вёрстка)

2023-08-27 12:38 UTC, Negodyaj commented on src/pages/Home/ReviewSection/ReviewSection.tsx
> +import 'swiper/css/pagination';
вот это прям плохо
ты должен импортировать вот эту хрень ровно 1 раз
в общем, тебе нужно инкапсулировать выбранную библиотеку в отдельном компоненте, чтоб всё остальное приложение не зависело от конкретного выбора

уже увидел, что дальше Семён про то же самое пишет

2023-08-27 12:40 UTC, SimonShvets commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +export const AboutUsSection = () => {
> я бы не был столь категоричен, потому как со стороны компонента Home эти теги section не видны)

какой смысл ? находимся в папке pages Home и так понятно что это компоненты внутри Home page)

2023-08-27 12:42 UTC, Negodyaj commented on src/pages/Home/WhyChooseUsSection/components/RightSideComponent/RightSideComponent.tsx
> +export const RightSideComponent = (props: RightSideComponentProps) => {
если пропсов много, то такой подход перестаёт быть удобным, и поэтому интерфейс всё равно нужен

деструткурирование при этом идёт в первой строчке кода компонента. типа const {a, b, c} = props;
это более общий подход, который удобен всегда

2023-08-27 12:52 UTC, Negodyaj commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +export const AboutUsSection = () => {
если какая-то секция тоже будет состоять из компонентов, не обязательно упарывается в лютую иерархичность и содавать components внутри этой секции
обычно просто кладуб папку компонента на одном уровне с секцией
потому что слишком глубокая иерархия - тож неудобно

2023-08-27 12:58 UTC, Dustikdev commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +          <SecondaryButton text={'LERN MORE'} status={''} />
на сайте LERN!))

2023-08-27 12:58 UTC, Dustikdev commented on src/components/Header/Header.tsx
> +import { useState } from 'react';
уберу

2023-08-27 12:58 UTC, SimonShvets commented on src/pages/Home/WhyChooseUsSection/components/RightSideComponent/RightSideComponent.tsx
> +export const RightSideComponent = (props: RightSideComponentProps) => {
> если пропсов много, то такой подход перестаёт быть удобным, и поэтому интерфейс всё равно нужен
> 
> деструткурирование при этом идёт в первой строчке кода компонента. типа const {a, b, c} = props; это более общий подход, который удобен всегда

это я и имел ввиду, просто такая штука const {a, b, c} = props; похожа на деструктор пропса)

2023-08-27 12:59 UTC, SimonShvets commented on src/pages/Home/WhyChooseUsSection/components/RightSideComponent/RightSideComponent.tsx
> +export const RightSideComponent = (props: RightSideComponentProps) => {
интерфейс нужен факт, вопросов нет, он остается

2023-08-27 12:59 UTC, Dustikdev commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +          <h3>Kyiv LuxeBouquets</h3>
у нас на главной фотка с названием салона)

2023-08-27 13:01 UTC, SimonShvets commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +          <h3>Kyiv LuxeBouquets</h3>
> у нас на главной фотка с названием салона)

надо бы найти новую, город можешь сам подобрать)) Антон попросил на лекции сменить по понятным причинам

2023-08-27 13:02 UTC, Dustikdev commented on src/pages/Home/HeroSection/HeroSection.scss
> +    .r-item {
это буквально буква R)

2023-08-27 13:05 UTC, Dustikdev commented on src/pages/Home/HeroSection/components/DescriptionBlock/DescriptionBlock.tsx
> +  if (props.direction === Direction.Left) {
я вообще не уверен в решении запилить отдельно енам для выбора из двух вариантов, сделал ради покодить. Переделаю на тернарник

2023-08-27 13:06 UTC, Dustikdev commented on src/pages/Home/Home.tsx
> +      <div className="our-service">
согласен, мне тоже глаз мозолит, сделаю компонент)

2023-08-27 13:07 UTC, Dustikdev commented on src/pages/Home/ReviewSection/ReviewSection.tsx
> +          <SwiperSlide>
можно, но у нас вроде свайперов больше нет нигде, я и так задолбался этот пилить)

2023-08-27 13:10 UTC, SimonShvets commented on src/pages/Home/ReviewSection/ReviewSection.tsx
> +          <SwiperSlide>
> можно, но у нас вроде свайперов больше нет нигде, я и так задолбался этот пилить)

посмотри внимательно Product page) там особо допиливать не надо, просто вынести в компонент отдельный и добавить нужные пропсы

2023-08-27 13:20 UTC, Dustikdev commented on src/components/TertiaryButton/TertiaryButton.scss
> +  }
согласен полностью, переделаю)

2023-08-27 13:22 UTC, Dustikdev commented on src/pages/Home/ReviewSection/ReviewSection.tsx
> +import 'swiper/css/pagination';
понял, сделаю

2023-08-29 12:52 UTC, SimonShvets requested changes

2023-08-29 12:52 UTC, SimonShvets commented on src/shared/assets/Facebook.svg
а почему эти с большой буквы?

2023-08-29 16:15 UTC, Dustikdev commented on src/_functions.scss
> +﻿@function calculate-vw($value) {
перенес в shared/mixins

2023-08-29 16:16 UTC, Dustikdev commented on src/components/Header/Header.tsx
> +import { useState } from 'react';
убрал

2023-08-29 16:17 UTC, Dustikdev commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +          <SecondaryButton text={'LERN MORE'} status={''} />
готово

2023-08-29 16:27 UTC, Dustikdev commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +          <h3>Kyiv LuxeBouquets</h3>
поправил картинку и все названия, если есть другие варики на картинку просто можно заменить в ассетах

2023-08-29 16:29 UTC, Dustikdev commented on src/pages/Home/AboutUsSection/AboutUsSection.tsx
> +export const AboutUsSection = () => {
мне удобно видеть при открытой структуре папок, что у меня секция, к примеру, внутри компонента Home называется как Section, а такой же компонент  в src - это не секция. Править не хочу, решение за Антоном. Если скажет - поправлю.

2023-08-29 16:29 UTC, Dustikdev commented on src/pages/Home/HeroSection/HeroSection.tsx
> +              Kyiv
готово

2023-08-29 16:35 UTC, Dustikdev commented on src/components/Header/Header.scss
> +      width: calculate-vw-mobile(24);
о чем ты? в мобильной версии нет в хедере фронтов, ну по крайней мере в нанешнем варианте.

2023-08-29 16:55 UTC, Dustikdev commented on src/pages/Home/HeroSection/components/DescriptionBlock/DescriptionBlock.tsx
> +  if (props.direction === Direction.Left) {
Я не уверен в правильности возвращения нескольких строк разметки в тернарнике, это банально смотрится неудобно. Про разметку img вообще не понял что ты имел ввиду. Я и с решением про енамы не уверен, надо ли так пилить @Negodyaj глянь, плз этот момент

2023-08-29 16:59 UTC, Dustikdev commented on src/pages/Home/Home.tsx
> +      <div className="our-service">
сделал

2023-08-29 17:56 UTC, Dustikdev commented on src/pages/Home/ReviewSection/ReviewSection.tsx
> +          <SwiperSlide>
сделал

2023-08-29 17:57 UTC, Dustikdev commented on src/pages/Home/WhyChooseUsSection/components/RightSideComponent/RightSideComponent.tsx
> +export const RightSideComponent = (props: RightSideComponentProps) => {
потому что у меня куча всего называется Right Side, так удобно не путаться

2023-08-29 17:59 UTC, Dustikdev commented on src/pages/Home/WhyChooseUsSection/components/RightSideComponent/RightSideComponent.tsx
> +export const RightSideComponent = (props: RightSideComponentProps) => {
ну спасибо за совет, по мне что так что так примерно одинаково, прям лишнего много не пишется

2023-08-29 18:01 UTC, Dustikdev commented on package.json
>    },
добавил

2023-08-29 18:03 UTC, Dustikdev commented on src/components/Header/Header.scss
> +}
сделано

2023-08-29 18:06 UTC, Dustikdev commented on src/components/Header/Header.scss
> +  }
сделано

2023-08-29 18:13 UTC, Dustikdev commented on src/components/TertiaryButton/TertiaryButton.scss
> +  }
@Negodyaj что то я повнимательнее посмотрел и понял, что все свойства, за исключением 3-4 у меня на трех кнопках разные, т.е. мне придется кучу другого все равно переписывать, есть ли смысл запариваться и писать отдельный класс? Плюс вопрос, а куда его ложить? В индекс? И в таком случае у меня будет по 2 класса применено в разметке, надо ли это?

2023-08-29 18:17 UTC, Dustikdev commented on src/pages/Home/HeroSection/HeroSection.scss
> +          }
тоже вопрос, именно с инлайном он мне нужен только в одном месте, в других я просто пишу font-style: italic. Непонятно, стоит ли делать стиль в котором будет просто указано, что это италик фонт и потом его дополнительно привязывать к разметке, или просто дописывать в css?
@Negodyaj

2023-08-29 18:18 UTC, Dustikdev commented on src/pages/Home/ReviewSection/ReviewSection.tsx
> +import 'swiper/css/pagination';
сделал @Negodyaj @SimonShvets возможно что то криво пильнул по архитектуре, поэтому просьба глянуть отдельно

2023-08-29 18:20 UTC, Dustikdev commented on src/shared/assets/Facebook.svg
поправил

2023-08-29 21:51 UTC, Negodyaj commented on src/pages/Home/HeroSection/HeroSection.scss
> +          }
у вас есть италик - и не инлайн? во дела)
ну ок тогда

2023-08-29 21:52 UTC, Negodyaj commented on src/components/TertiaryButton/TertiaryButton.scss
> +  }
2 класса в вёрстке - это вполне норм)

2023-08-29 21:57 UTC, Negodyaj commented on src/components/ReactSwiper/ReactSwiper.tsx
> +export interface Items {
интерфейс в единственном числе назвать надо)
потому как ты описываешь ровно 1 элемент)

другой момент
сейчас этот компонент работат только с объектами определённого типа. и если мне понадобится сделать карусельку, но с другими данными, я этот компонент использовать не смогу. а хотелось бы

поэтому вместо items лучше сделать children: ReactNode | ReactNode[]
(то, что мы на занятии делали)

2023-08-30 00:30 UTC, Dustikdev commented on src/components/ReactSwiper/ReactSwiper.tsx
> +export interface Items {
сделал

2023-08-30 00:35 UTC, Negodyaj approved these changes

2023-08-30 06:59 UTC, SimonShvets approved these changes

2023-08-30 07:02 UTC, SimonShvets commented
апрувнул, мерджи только с опцией rebase and merge, только перед этим обязательно засквош комиты в один, названием коммита будет название ветки - issue-001/subtask/issue-003/home-page-desktop-implementation

2023-08-30 15:07 UTC, merged