Feature/issue 007/about us page implementation
IIWPEOJ-Inc/FlowersStore pull request #27
Opened 2023-09-15 13:17 UTC by SimonShvets

2023-09-15 13:59 UTC, Dustikdev requested changes
вроде больше ничо не нашел

2023-09-15 13:59 UTC, Dustikdev commented on src/pages/aboutUs/aboutUs.scss
> +    border-bottom: 1px solid #121212;
чота тут двойной бордер получается с футером

2023-09-15 13:59 UTC, Dustikdev commented on src/pages/aboutUs/aboutUs.tsx
> +          <p className="text-centred" style={isDesktop ? { width: '50%' } : {}}>
ну типо инлайн стили моветон, но я сам не против

2023-09-15 13:59 UTC, Dustikdev commented on src/pages/aboutUs/aboutUs.tsx
> +            LuxeBouquets was founded in 2010 by Natalia Zelinska with the goal of bringing unique and exquisite bouquets to the people of Kyiv.
ну типо история про киев, а у нас монреаль, но я хз, надо ли париться

2023-09-15 13:59 UTC, Dustikdev commented on src/pages/aboutUs/aboutUs.scss
> +        }
не могу понять почему, но гап в 2 раза почти меньше, чем должен быть

2023-09-16 06:29 UTC, SimonShvets commented on src/pages/aboutUs/aboutUs.scss
> +        }
@Dustikdev все согласно макету, бага локально не увидел, пришли скрин

2023-09-16 06:30 UTC, SimonShvets commented on src/pages/aboutUs/aboutUs.tsx
> +          <p className="text-centred" style={isDesktop ? { width: '50%' } : {}}>
@Negodyaj это к тебе, могу подвинуть в className

2023-09-16 07:09 UTC, SimonShvets commented on src/pages/aboutUs/aboutUs.scss
> +    border-bottom: 1px solid #121212;
поправил

2023-09-16 07:19 UTC, Dustikdev commented on src/pages/aboutUs/aboutUs.scss
> +        }
<img width="1327" alt="Снимок экрана 2023-09-16 в 14 15 32" src="https://github.com/IIWPEOJ-Inc/FlowersStore/assets/92670124/04c50799-5e73-419f-a573-3113a238ec31">
<img width="442" alt="Снимок экрана 2023-09-16 в 14 18 00" src="https://github.com/IIWPEOJ-Inc/FlowersStore/assets/92670124/08e95092-9be0-4dc7-b230-4f9dd9e3f354">
судя по всему у тебя почему то не применяется стиль с таблетки

2023-09-16 07:31 UTC, SimonShvets commented on src/pages/aboutUs/aboutUs.scss
> +        }
@Dustikdev спасибо за замечание, поправил!

2023-09-16 07:39 UTC, Dustikdev approved these changes

2023-09-16 20:51 UTC, Negodyaj commented on src/pages/aboutUs/aboutUs.tsx
> +          <p className="text-centred" style={isDesktop ? { width: '50%' } : {}}>
моветон) уноси)

2023-09-16 20:51 UTC, Negodyaj commented on src/pages/aboutUs/aboutUs.tsx
> +              <div className="icon-container">
этот див точно нужен? если линку дать класс icon-container, не выйдет то же самое?

2023-09-16 20:51 UTC, Negodyaj commented on src/pages/aboutUs/aboutUs.tsx
> +        {isDesktop ? (
если на мобилке меняется только порядок этих двух чайлдов, то дублировать вёрстку - эт самое плохое решение из всех)
потому что ты мог дать нужному чайлду провертю order
ну или выставить grid-column: 1/2

но не копи-паста же)

2023-09-16 20:51 UTC, Negodyaj commented on src/pages/aboutUs/aboutUs.tsx
> +            {
эта скобка не нужна

2023-09-16 20:51 UTC, Negodyaj commented on src/pages/aboutUs/aboutUs.tsx
> +            }
эта скобка не нужна

2023-09-16 20:51 UTC, Negodyaj commented on src/pages/aboutUs/aboutUs.tsx
> +            {<img src={Image3} alt="img-about-us-3" className="img-about-us border-bottom" />}
и тут скобки не нужны

2023-09-17 12:57 UTC, Negodyaj approved these changes

2023-09-17 15:22 UTC, merged